# Generated by Django 6.0.7 on 2026-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0004_alter_patient_options_alter_patient_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
