# Generated by Django 6.0.7 on 2026-07-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0005_prescription_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='UNPAID', max_length=20)),
                ('payment_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.appointment')),
            ],
            options={
                'verbose_name': 'billing',
                'verbose_name_plural': 'billings',
                'db_table': 'billings',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_result', models.FileField(blank=True, null=True, upload_to='upload_result/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='pdf_report/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.appointment')),
            ],
            options={
                'verbose_name': 'laboratory',
                'verbose_name_plural': 'laboratories',
                'db_table': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('analysis', models.TextField()),
                ('attachments', models.FileField(blank=True, upload_to='records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.patient')),
            ],
            options={
                'verbose_name': 'medical record',
                'verbose_name_plural': 'medical records',
                'db_table': 'medical records',
            },
        ),
    ]
