# Generated by Django 6.0.7 on 2026-07-11 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0006_billing_laboratory_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='attachments',
            new_name='rentgen_file',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_history',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partial Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='work_schedule',
            field=models.TextField(),
        ),
    ]
