# Generated by Django 6.0.7 on 2026-07-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0007_rename_attachments_medicalrecord_rentgen_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
