# Generated by Django 6.0.7 on 2026-07-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0008_appointment_is_reminded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-created_at'], 'verbose_name': 'billing', 'verbose_name_plural': 'billings'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['-created_at'], 'verbose_name': 'laboratory', 'verbose_name_plural': 'laboratories'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'medical record', 'verbose_name_plural': 'medical records'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'prescription', 'verbose_name_plural': 'prescriptions'},
        ),
    ]
