# Generated by Django 6.0.7 on 2026-07-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient'), ('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('LAB_TECHNICIAN', 'Lab_Technician')], default='ADMIN', max_length=20),
        ),
    ]
