name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # BAZA VA REDIS NI SHU YERDA ISHGA TUSHIRAMIZ
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: Management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "1"
        ports:
          - 5432:5432
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        env:
          # Actions ichida "db" hosti localhost bo'ladi
          DB_HOST: localhost
          DB_NAME: Management
          DB_USER: postgres
          DB_PASSWORD: "1"
          SECRET_KEY: test-key-123
        run: python manage.py test clinicapp.tests